# Analyzer configuration for Digital Certificate Repository
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Context usage in async functions - disabled because we use mounted checks
    use_build_context_synchronously: false
    
    # Code style preferences (optional - can be disabled if too strict)
    prefer_single_quotes: true
    
    # Disable some style checks to focus on important issues
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    curly_braces_in_flow_control_structures: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    avoid_print: false
    
    # Keep important checks enabled - commented out as not recognized in current Flutter version
    # unused_import: true
    # unused_field: true  
    # unused_element: true
    # dead_code: true
    
    # sort_constructors_first: true  # Uncomment if you want strict constructor ordering
    # sort_unnamed_constructors_first: true  # Uncomment if you want strict constructor ordering
