name: digital_certificate_repository
description: A secure, scalable mobile application that serves as a Digital Certificate Repository for Certificate Authorities and recipients.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4  
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  cloud_functions: ^5.5.1
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # HTTP and API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage and Security
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # PDF and Document Handling
  pdf: ^3.10.8
  printing: ^5.11.1
  csv: ^6.0.0
  excel: ^4.0.1
  
  # File Handling
  file_picker: ^8.0.6
  image_picker: ^1.0.4
  image: ^4.1.7
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # QR Code and Sharing
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  share_plus: ^7.2.1
  url_launcher: ^6.3.0
  
  # Form Validation and Input
  email_validator: ^2.1.17
  intl: ^0.19.0
  form_field_validator: ^1.1.0
  
  # Animations
  flutter_staggered_animations: ^1.1.1
  animate_do: ^3.1.2
  
  # Charts and Graphs
  fl_chart: ^0.68.0
  
  # Utilities
  uuid: ^4.3.3
  crypto: ^3.0.3
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  html: ^0.15.4
  logger: ^2.0.2+1

  # Payment Gateway (Bonus)
  flutter_stripe: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing and Build tools
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
