// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOC92kC8R8Irojea4IGTW8yA71bzfP6aA',
    appId: '1:816767361642:web:d18b39e3e3b18004e66013',
    messagingSenderId: '816767361642',
    projectId: 'mobile-project-63d46',
    authDomain: 'mobile-project-63d46.firebaseapp.com',
    storageBucket: 'mobile-project-63d46.firebasestorage.app',
    measurementId: 'G-H3NV75DTBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHyc9BrC6YB0ZlYBEkjAhJfatBsZcfv8',
    appId: '1:816767361642:android:3b59a26c4dc0280ae66013',
    messagingSenderId: '816767361642',
    projectId: 'mobile-project-63d46',
    storageBucket: 'mobile-project-63d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhjJZn-lE1mA9DNk8QilpJAs4t_OCNeU8',
    appId: '1:816767361642:ios:ed7ca0128170681de66013',
    messagingSenderId: '816767361642',
    projectId: 'mobile-project-63d46',
    storageBucket: 'mobile-project-63d46.firebasestorage.app',
    androidClientId: '816767361642-mpu910e8c0pj35d3hkbuscb0hjo3mjmn.apps.googleusercontent.com',
    iosClientId: '816767361642-63apffsvoltcpia85erso5oa3blftehe.apps.googleusercontent.com',
    iosBundleId: 'com.upm.certrepository.digitalCertificateRepository',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhjJZn-lE1mA9DNk8QilpJAs4t_OCNeU8',
    appId: '1:816767361642:ios:ed7ca0128170681de66013',
    messagingSenderId: '816767361642',
    projectId: 'mobile-project-63d46',
    storageBucket: 'mobile-project-63d46.firebasestorage.app',
    androidClientId: '816767361642-mpu910e8c0pj35d3hkbuscb0hjo3mjmn.apps.googleusercontent.com',
    iosClientId: '816767361642-63apffsvoltcpia85erso5oa3blftehe.apps.googleusercontent.com',
    iosBundleId: 'com.upm.certrepository.digitalCertificateRepository',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOC92kC8R8Irojea4IGTW8yA71bzfP6aA',
    appId: '1:816767361642:web:d18b39e3e3b18004e66013',
    messagingSenderId: '816767361642',
    projectId: 'mobile-project-63d46',
    authDomain: 'mobile-project-63d46.firebaseapp.com',
    storageBucket: 'mobile-project-63d46.firebasestorage.app',
    measurementId: 'G-H3NV75DTBT',
  );

}